### ISSUE TITLE
Пароль не шифруется при обновлении пользователя

### ISSUE THREAD

**Issue by AlibabaRazboinik** [AlibabaRazboinik/habit_tracker#112]
1) Регистрируемся
2) Логинимся
3) Обновляем пользователя

Ожидание: в бд пароль зашифрован
Реальность: в бд попал открытый пароль

**Comment by lkorasik** [comment]
Возможно поправил в #124

**Comment by lkorasik** [comment]
Для ветки dev задача более не актуальна
