### ISSUE TITLE
Нет проверки на доступ к ресурсам

### ISSUE THREAD

**Issue by AlibabaRazboinik** [AlibabaRazboinik/habit_tracker#113]
Кейс: 
1) Регистрируем Kennedy
2) Входим под Kennedy
3) Создаем две привычки
4) Проверяем, что в бд есть два пользователя. Две привычки, которые принадлежат Kennedy
5) Регистрируем Kennedy2
6) Входим под Kennedy2
7) Создаем две привычки
8) Проверяем, что в бд есть два пользователя. Четыре привычки, две принадлежат Kennedy, две - Kennedy2
9) Удаляем привычки у Kennedy

Ожидание: сообщение о том, что у Kennedy2 нет таких прав.
Реальность: привычка успешно была удалена.

Починить этот кейс и проверить аналогичные.

Статья, которая описывает механизм: https://sysout.ru/vvedenie-v-spring-security-acl/

**Comment by lkorasik** [comment]
Дублируется задачей #136
